[project]
    name = "OC-pytest-buildkite"
    version=0.1

[tool.towncrier]
    package = "pytest_buildkite"
    package_dir = "app"
    filename = "NEWS.rst"

[tool.setuptools]
    packages = ["pytest_buildkite"]
